name: macOSCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
    DOTNETVERSION: 6.0.300

jobs:
  buildmacCatalyst:
    runs-on: macos-12
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version:  '${{env.DOTNETVERSION}}'
          
      - name: List installed .NET info
        shell: pwsh
        run: dotnet --info

      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet nuget locals all --clear 
          dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
    
      - name: Restore nuget packages
        run: |
          dotnet restore Preferences.sln
        
        # https://docs.microsoft.com/en-us/dotnet/maui/macos/deployment/overview
      - name : Build MacCatalyst App
        shell: bash
        run: |
          dotnet build -f net6.0-maccatalyst -c Release -o ./artifacts
          dotnet publish -f net6.0-maccatalyst -c Release -p:BuildIpa=True -o ./artifacts
          
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts-mac
          path: |
            **
